Movie/Movie/Controllers/Admin/LogVisitController.cs
using Movie.Models.Component;
using Movie.Models.Dao;
using Movie.Models.Dto;
using OfficeOpenXml;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Movie.Controllers.Admin
{
    public class LogVisitController : Controller
    {
        Permission checkuser = new Permission();
        // GET: LogVisit
        public ActionResult Index(string start_date, string stop_date, int? page)
        {
            checkuser.chkrights("admin");
            int rows = Util.NVLInt(Varible.Config.page_rows);
            if (page != null)
            {
                if (page >= 1)
                {
                    start_date = Session["start_date"].ToString();
                    stop_date = Session["stop_date"].ToString();
                }
            }
            else
            {
                if (start_date == null)
                {
                    Session["start_date"] = Util.NVLString(Cv.Date(DateTime.Now.ToString("yyyyMMdd")));
                    Session["stop_date"] = Util.NVLString(Cv.Date(DateTime.Now.ToString("yyyyMMdd")));
                }
                else
                {
                    Session["start_date"] = start_date;
                    Session["stop_date"] = stop_date;
                }
            }
            start_date = start_date != null ? start_date + " " + "00:00:00" : Util.NVLString(Cv.Date(DateTime.Now.ToString("yyyyMMdd00:00:00")));
            stop_date = stop_date != null ? stop_date + " " + "23:59:59" : Util.NVLString(Cv.Date(DateTime.Now.ToString("yyyyMMdd23:59:59")));
            var data = VisitListDao.Instance.GetDataList(start_date, stop_date);
            TempData["start_date"] = Session["start_date"];
            TempData["stop_date"] = Session["stop_date"];
            TempData["data"] = data.ToList().ToPagedList(page ?? 1, rows);
            Session["count"] = data.Count;
            ViewBag.Count = Session["count"];
            Session["Rows"] = rows;
            return View(TempData["data"]);
        }

        public ActionResult Search(string drp, string keyword, int? page)
        {
            checkuser.chkrights("admin");
            var data = VisitListDao.Instance.GetDataList();
            int rows = Util.NVLInt(Varible.Config.page_rows);
            TempData["data"] = data.ToList().ToPagedList(page ?? 1, rows);
            TempData["data1"] = data.ToList();
            TempData["keyword"] = keyword;
            int cnt = data.ToList().Count;
            Session["count"] = cnt;
            ViewBag.Rows = rows;
            Session["data"] = TempData["data1"];
            ViewBag.Count = cnt;
            return View(TempData["data"]);
        }
        public ActionResult ExportToExcel()
        {
            try
            {
                var data = Session["data"] as List<LogDto>;
                if (data != null)
                {
                    ExcelPackage.LicenseContext = LicenseContext.Commercial;
                    ExcelPackage.LicenseContext = LicenseContext.NonCommercial;
                    ExcelPackage Ep = new ExcelPackage();
                    ExcelWorksheet Sheet = Ep.Workbook.Worksheets.Add("Report");
                    Sheet.Cells["A1"].Value = "IP";
                    Sheet.Cells["B1"].Value = "접속 경로";
                    Sheet.Cells["C1"].Value = "브라우저";
                    Sheet.Cells["D1"].Value = "OS";
                    Sheet.Cells["E1"].Value = "접속기기";
                    Sheet.Cells["F1"].Value = "일시";
                    int row = 2;
                    foreach (var item in data)
                    {
                        Sheet.Cells[string.Format("A{0}", row)].Value = item.ip.ToString();
                        Sheet.Cells[string.Format("B{0}", row)].Value = item.url.ToString();
                        Sheet.Cells[string.Format("C{0}", row)].Value = item.browser.ToString();
                        Sheet.Cells[string.Format("D{0}", row)].Value = item.system_os.ToString();
                        Sheet.Cells[string.Format("E{0}", row)].Value = item.connect_hardware.ToString();
                        Sheet.Cells[string.Format("F{0}", row)].Value = item.start_date.ToString();
                        row++;
                    }
                    Sheet.Cells["A:AZ"].AutoFitColumns();
                    Response.Clear();
                    Response.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
                    Response.AddHeader("content-disposition", "attachment: filename=" + "Report.xlsx");
                    Response.BinaryWrite(Ep.GetAsByteArray());
                    Response.End();
                }
                ViewBag.Count = Session["count"];
                ViewBag.Rows = Util.NVLInt(Varible.Config.page_rows);

                return View("Index");
            }
            catch (Exception e)
            {
                return RedirectToAction("Index");
            }
        }
    }
}

Movie/Movie/Views/LogVisit/Index.cshtml
@using PagedList;
@using PagedList.Mvc;
@model IPagedList<Movie.Models.Dto.LogDto>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout_admin.cshtml"; ;
}

<div class="main-panel">
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
        <div class="container-fluid">
            @*<div class="navbar-wrapper">
                <a class="navbar-brand" href="javascript:;">MOVIES LIST / ภาพยนต์</a>
            </div>*@
            <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
                <span class="sr-only">Toggle navigation</span>
                <span class="navbar-toggler-icon icon-bar"></span>
                <span class="navbar-toggler-icon icon-bar"></span>
                <span class="navbar-toggler-icon icon-bar"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-end">
                <form class="navbar-form">
                    <div class="input-group no-border">
                        <input type="text" value="" class="form-control" placeholder="Search...">
                        <button type="submit" class="btn btn-white btn-round btn-just-icon">
                            <i class="material-icons">search</i>
                            <div class="ripple-container"></div>
                        </button>
                    </div>
                </form>
                <ul class="navbar-nav">
                    <li class="nav-item dropdown">
                        <a class="nav-link" href="javascript:;" id="navbarDropdownProfile" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="material-icons">person</i>
                            <p class="d-lg-none d-md-block">
                                Account
                            </p>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownProfile">
                            <a class="dropdown-item" href="@Url.Action("Index","MemberList")">Settings</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="~/Login/LogOut">Log out</a>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- End Navbar -->
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header card-header-primary">
                            <h4 class="card-title ">USER VISIT / จำนวนการเข้าถึง</h4>
                        </div>
                        <div class="card-body">
                            <div style="float:right">
                                @using (Html.BeginForm("ExportToExcel", "LogVisit", FormMethod.Post))
                                {
                                    <button type="submit" id="btnExport" style="margin-top:-10px;" class="btn btn-rounded btn-warning"><i class="icon-printer mr-2"></i> Export</button>
                                }
                            </div>
                            <div class="table-responsive">
                                <table class="table">
                                    <tr class=" text-primary">
                                        <th class="align-middle" style="width:50px;">No</th>
                                        <th class="align-middle" style="width:120px;">IP</th>
                                        <th class="align-middle">Url Address</th>
                                        <th class="align-middle" style="width:150px;">Browser</th>
                                        <th class="align-middle" style="width:300px;">OS</th>
                                        <th class="align-middle" style="width:90px;">Device</th>
                                        <th class="align-middle" style="width:200px;">Date</th>
                                    </tr>
                                    <tbody>
                                        @if (Model != null && Model.Count() != 0)
                                        {
                                            foreach (var item in Model)
                                            {
                                                <tr class="text-center">
                                                    <td> @Html.DisplayFor(modelItem => item.num)</td>
                                                    <td> @Html.DisplayFor(modelItem => item.ip)</td>
                                                    <td class="text-left"> @Html.DisplayFor(modelItem => item.url)</td>
                                                    <td> @Html.DisplayFor(modelItem => item.browser)</td>
                                                    <td> @Html.DisplayFor(modelItem => item.system_os)</td>
                                                    <td> @Html.DisplayFor(modelItem => item.connect_hardware)</td>
                                                    <td> @Html.DisplayFor(modelItem => item.start_date)</td>
                                                </tr>
                                            }
                                        }
                                        else
                                        {
                                            <tr class="text-center">
                                                <td colspan="6">
                                                    No Data !!
                                                </td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                            @{
                                if (Convert.ToInt32(ViewBag.Count) > ViewBag.Rows)
                                {
                                    <div class="justify-content-center row">
                                        @if (Model != null)
                                        {
                                            @Html.PagedListPager(Model, Page => Url.Action("Index", "LogVisit", new { Page }))
                                        }
                                    </div>
                                }
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Movie/Movie/Views/LogVisit/Search.cshtml
@using PagedList;
@using PagedList.Mvc;
@model IPagedList<Movie.Models.Dto.LogDto>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout_admin.cshtml"; ;
}
<div class="main-panel">
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
        <div class="container-fluid">
            @*<div class="navbar-wrapper">
                <a class="navbar-brand" href="javascript:;">MOVIES LIST / ภาพยนต์</a>
            </div>*@
            <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
                <span class="sr-only">Toggle navigation</span>
                <span class="navbar-toggler-icon icon-bar"></span>
                <span class="navbar-toggler-icon icon-bar"></span>
                <span class="navbar-toggler-icon icon-bar"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-end">
                <form class="navbar-form">
                    <div class="input-group no-border">
                        <input type="text" value="" class="form-control" placeholder="Search...">
                        <button type="submit" class="btn btn-white btn-round btn-just-icon">
                            <i class="material-icons">search</i>
                            <div class="ripple-container"></div>
                        </button>
                    </div>
                </form>
                <ul class="navbar-nav">
                    <li class="nav-item dropdown">
                        <a class="nav-link" href="javascript:;" id="navbarDropdownProfile" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="material-icons">person</i>
                            <p class="d-lg-none d-md-block">
                                Account
                            </p>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownProfile">
                            <a class="dropdown-item" href="@Url.Action("Index","MemberList")">Settings</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="~/Login/LogOut">Log out</a>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- End Navbar -->
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header card-header-primary">
                            <h4 class="card-title ">USER VISIT / จำนวนการเข้าถึง</h4>
                        </div>
                        <div class="card-body">
                            <div style="float:right">
                                @using (Html.BeginForm("ExportToExcel", "LogVisit", FormMethod.Post))
                                {
                                    <button type="submit" id="btnExport" style="margin-top:-10px;" class="btn btn-rounded btn-warning"><i class="icon-printer mr-2"></i> Export</button>
                                }
                            </div>
                            <div class="table-responsive">
                                <table class="table">
                                    <tr class=" text-primary">
                                        <th class="align-middle" style="width:50px;">No</th>
                                        <th class="align-middle" style="width:120px;">IP</th>
                                        <th class="align-middle">Url Address</th>
                                        <th class="align-middle" style="width:150px;">Browser</th>
                                        <th class="align-middle" style="width:300px;">OS</th>
                                        <th class="align-middle" style="width:90px;">Device</th>
                                        <th class="align-middle" style="width:200px;">Date</th>
                                    </tr>
                                    <tbody>
                                        @if (Model != null && Model.Count() != 0)
                                        {
                                            foreach (var item in Model)
                                            {
                                                <tr class="text-center">
                                                    <td> @Html.DisplayFor(modelItem => item.num)</td>
                                                    <td> @Html.DisplayFor(modelItem => item.ip)</td>
                                                    <td class="text-left"> @Html.DisplayFor(modelItem => item.url)</td>
                                                    <td> @Html.DisplayFor(modelItem => item.browser)</td>
                                                    <td> @Html.DisplayFor(modelItem => item.system_os)</td>
                                                    <td> @Html.DisplayFor(modelItem => item.connect_hardware)</td>
                                                    <td> @Html.DisplayFor(modelItem => item.start_date)</td>
                                                </tr>
                                            }
                                        }
                                        else
                                        {
                                            <tr class="text-center">
                                                <td colspan="6">
                                                    No Data !!
                                                </td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                            @{
                                if (Convert.ToInt32(ViewBag.Count) > ViewBag.Rows)
                                {
                                    <div class="justify-content-center row">
                                        @if (Model != null)
                                        {
                                            @Html.PagedListPager(Model, Page => Url.Action("Index", "LogVisit", new { Page }))
                                        }
                                    </div>
                                }
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>