Movie/Movie/Controllers/Admin/MemberListController.cs
using Movie.Models.Component;
using Movie.Models.Dao;
using Movie.Models.Dto;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
namespace Movie.Controllers.Admin
{
    public class MemberListController : Controller
    {
        Permission checkuser = new Permission();
        // GET: MemberList
        public ActionResult Index(int? page)
        {
            if (ModelState.IsValid)
            {
                checkuser.chkrights("admin");
                var model = MemberListDao.Instance.GetDataList().Find(smodel => smodel.id == Varible.User.member_id);
                var data = MemberListDao.Instance.GetDataList();
                int rows = Util.NVLInt(Varible.Config.page_rows);
                var count = data.Count;
                TempData["data1"] = data.ToList();
                return View(model);
            }
            else
            {
                return View();
            }

        }
        public ActionResult ChkUserID(string pUid, string user_id)
        {
            try
            {
                bool result = LoginDao.Instance.ChkUser(pUid, user_id);
                if (result == false)// false = ไม่มี username นี้
                {
                    return Json(new returnsave { err = "0", errmsg = "사용 가능한 아이디 입니다.\n회원가입을 진행해 주세요." });
                }
                else
                {
                    //Session["member_id"] = member_id;
                    return Json(new returnsave { err = "1", errmsg = "사용중인 아이디 입니다. 다른 아이디를 입력해 주세요." });
                }
            }
            catch (Exception e)
            {
                return Json(new returnsave { err = "0", errmsg = "Error" });
            }


            //return objreturnsave;
        }
        public ActionResult Create()
        {
            checkuser.chkrights("admin");
            return View();
        }
        int member_id = 0;
        // POST: MemberList/Create

    }
}

Movie/Movie/Views/MemberList/Index.cshtml
@model Movie.Models.Dto.MemberListDto
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout_admin.cshtml";
}
@Html.ValidationSummary(true, "", new { @class = "text-danger" })
@Html.HiddenFor(model => model.id)
<div class="main-panel">
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
        <div class="container-fluid">
            @*<div class="navbar-wrapper">
                <a class="navbar-brand" href="javascript:;">MOVIES LIST / ภาพยนต์</a>
            </div>*@
            <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
                <span class="sr-only">Toggle navigation</span>
                <span class="navbar-toggler-icon icon-bar"></span>
                <span class="navbar-toggler-icon icon-bar"></span>
                <span class="navbar-toggler-icon icon-bar"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-end">
                <form class="navbar-form">
                    <div class="input-group no-border">
                        <input type="text" value="" class="form-control" placeholder="Search...">
                        <button type="submit" class="btn btn-white btn-round btn-just-icon">
                            <i class="material-icons">search</i>
                            <div class="ripple-container"></div>
                        </button>
                    </div>
                </form>
                <ul class="navbar-nav">
                    <li class="nav-item dropdown">
                        <a class="nav-link" href="javascript:;" id="navbarDropdownProfile" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="material-icons">person</i>
                            <p class="d-lg-none d-md-block">
                                Account
                            </p>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownProfile">
                            <a class="dropdown-item" href="@Url.Action("Index","MemberList")">Settings</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="~/Login/LogOut">Log out</a>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- End Navbar -->
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header card-header-primary">
                            <h4 class="card-title">USER PROFILE / ช้อมูลส่วนตัว</h4>
                        </div>
                        <div class="card-body">
                            <form>
                                <div class="row">
                                    <div class="col-md-5">
                                        <div class="form-group">
                                            <label class="bmd-label-floating">Company (disabled) / ชื่อบริษัท</label>
                                            <input type="text" class="form-control" disabled>
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label class="bmd-label-floating">Username / รหัสสมาชิก</label>
                                            <input type="text" class="form-control" disabled value="@Html.DisplayFor(model => model.username)">
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <label class="bmd-label-floating">Email address / อีเมลล์</label>
                                            <input type="email" class="form-control" disabled>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="bmd-label-floating">Fist Name / ชื่อ</label>
                                            <input type="text" class="form-control" disabled>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="bmd-label-floating">Last Name / นามสกุล</label>
                                            <input type="text" class="form-control" disabled>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <label class="bmd-label-floating">Provide / เมื่อง</label>
                                            <input type="text" class="form-control" disabled>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <label class="bmd-label-floating">Country / ประเทศ</label>
                                            <input type="text" class="form-control" disabled>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <label class="bmd-label-floating">Postal Code / รหัสไปษณีย์</label>
                                            <input type="text" class="form-control" disabled>
                                        </div>
                                    </div>
                                </div>
                                <button type="submit" class="btn btn-primary pull-right">Update Profile</button>
                                <div class="clearfix"></div>
                            </form>
                        </div>
                    </div>
                </div>
                
            </div>
        </div>
    </div>
    
</div>