Movie/Movie/Controllers/Admin/MenubarController.cs
using Movie.Models.Component;
using Movie.Models.Dao;
using Movie.Models.Dto;
using PagedList;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DocumentFormat.OpenXml.Office2010.Excel;
using MySqlConnector;
using System.Data;

namespace Movie.Controllers.Admin
{
    public class MenubarController : Controller
    {
        Permission checkuser = new Permission();
        // GET: Menubar
        public ActionResult Index(int? page)
        {
            checkuser.chkrights("admin");
            var data = MenubarListDao.Instance.GetDataList();
            string count = string.Empty;
            if (data.Count < 1000)
            {
                count = data.Count.ToString();
            }
            else
            {
                count = data.Count.ToString("0,0", CultureInfo.InvariantCulture);
            }

            int rows = Util.NVLInt(Varible.Config.page_rows);
            ViewBag.Count = count;
            ViewBag.Rows = rows;
            return View(data.ToList().ToPagedList(page ?? 1, rows));
        }
        public ActionResult AddBar()
        {
            ViewBag.menubar_type = DropdownDao.Instance.GetDataType();
            return View();
        }
        [HttpPost]
        public ActionResult AddBar(MenubarListDto model)
        {
            try
            {
                string result = MenubarListDao.Instance.SaveDataList(model, "add");
                if (result != "OK")
                {
                    ViewBag.Message = result;
                    ModelState.Clear();
                }
                else
                {
                    ViewBag.menubar_type = DropdownDao.Instance.GetDataType();
                    ViewBag.Message = "Successfully !!";
                    //KRPBL.Component.Common.Form.SetAlertMessage(this,"ไม่พบ User ID ที่ระบุ กรุณาตรวจสอบ");
                    ModelState.Clear();
                }
                return View();
            }
            catch (Exception e)
            {
                ViewBag.Message = "Error : " + e.Message;
                return View();
            }
        }
        public ActionResult Edit(int id)
        {
            var model = MenubarListDao.Instance.GetDataList().Find(smodel => smodel.id == id);
            ViewBag.menubar_type = DropdownDao.Instance.GetDataType();
            return View(model);
        }
        // POST: ContentList/Edit/5
        [HttpPost]
        public ActionResult Edit(MenubarListDto model)
        {
            try
            {

                string result = MenubarListDao.Instance.SaveDataList(model, "edit");
                if (result != "OK")
                {
                    ViewBag.Message = result;
                }
                else
                {
                    return RedirectToAction("Index");
                }
                return View();
            }
            catch
            {
                return View();
            }
        }
        public ActionResult DeleteBar(MenubarListDto model)
        {
            try
            {
                string result = MenubarListDao.Instance.SaveDataMenuList(model, "del");
                if (result == "OK")
                {
                    ViewBag.Message = "Student Deleted Successfully";
                }
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                ViewBag.Message = "Error : " + e.Message.ToString();
                return View();
            }
        }
    }
}

Movie/Movie/Views/Menubar/AddBar.cshtml
@model Movie.Models.Dto.MenubarListDto
@{
    ViewBag.Title = "AddBar";
    Layout = "~/Views/Shared/_Layout_admin.cshtml"; ;
}
@using (Html.BeginForm("AddBar", "Menubar"))
{
    @Html.AntiForgeryToken()

    <div class="main-panel">
        <!-- End Navbar -->
        <div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-12 ml-auto mr-auto">
                        <div class="card">
                            <div class="card-header card-header-primary">
                                <h4 class="card-title">MANAGE / การจัดการ</h4>
                                <p class="card-category">@Html.ValidationSummary(true, "", new { @class = "text-danger" })</p>
                            </div>
                            <div class="card-body">
                                <h4 class="card-title">@ViewBag.Message</h4>
                                <div class="table-responsive table-upgrade">
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th style="text-align:center;">Side Tab / ตำเเหน่งแท็บ 1(บน) 2(ซ้าย) 3(ขวา)</th>
                                                <th style="width:70%;" class="text-center">Side Name / ชื่อประเภท </th>
                                                @*<th class="text-center">File / ไฟล์</th>*@
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>
                                                    @Html.DropDownListFor(model => model.type, new SelectList(ViewBag.menubar_type, "Value", "Text"), new { @class = "form-control" })
                                                </td>
                                                <td class="text-center">
                                                    @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                                                    @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })

                                                </td>
                                                @*<td class="text-center">
                                                        <input type="file" value="@Url.Action("UploadFile", "MovieList")" name="UploadButton" id="UploadButton" />
                                                    </td>*@
                                            </tr>
                                        </tbody>
                                    </table>
                                    <div class="form-group text-center">
                                        <div class="col-md-offset-2 col-md-12">
                                            <input type="button" value="Back" onclick="location.href='@Url.Action("Index", "Menubar")'" class="btn btn-danger" />
                                            <input type="submit" value="Save" class="btn btn-primary" />
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

}

Movie/Movie/Views/Menubar/Edit.cshtml
@model Movie.Models.Dto.MenubarListDto
@{
    ViewBag.Title = "AddBar";
    Layout = "~/Views/Shared/_Layout_admin.cshtml"; ;
}
@using (Html.BeginForm("Edit", "Menubar"))
{
    @Html.AntiForgeryToken()

    <div class="main-panel">
        <!-- End Navbar -->
        <div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-12 ml-auto mr-auto">
                        <div class="card">
                            <div class="card-header card-header-primary">
                                <h4 class="card-title">MANAGE / การจัดการ</h4>
                                <p class="card-category">@Html.ValidationSummary(true, "", new { @class = "text-danger" })</p>
                            </div>
                            <div class="card-body">
                                <h4 class="card-title">@ViewBag.Message</h4>
                                <div class="table-responsive table-upgrade">
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th style="text-align:center;">Side Tab / ตำเเหน่งแท็บ 1(บน) 2(ซ้าย) 3(ขวา)</th>
                                                <th style="width:70%;" class="text-center">Side Name / ชื่อประเภท </th>
                                                @*<th class="text-center">File / ไฟล์</th>*@
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>
                                                    @Html.DropDownListFor(model => model.type, new SelectList(ViewBag.menubar_type, "Value", "Text"), new { @class = "form-control" })
                                                </td>
                                                <td class="text-center">
                                                    @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                                                    @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })

                                                </td>
                                                @*<td class="text-center">
                                                        <input type="file" value="@Url.Action("UploadFile", "MovieList")" name="UploadButton" id="UploadButton" />
                                                    </td>*@
                                            </tr>
                                        </tbody>
                                    </table>
                                    <div class="form-group text-center">
                                        <div class="col-md-offset-2 col-md-12">
                                            <input type="button" value="Back" onclick="location.href='@Url.Action("Index", "Menubar")'" class="btn btn-danger" />
                                            <input type="submit" value="Save" class="btn btn-primary" />
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

}

Movie/Movie/Views/Menubar/Index.cshtml
@using PagedList;
@using PagedList.Mvc;
@model IPagedList<Movie.Models.Dto.MenubarListDto>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout_admin.cshtml";
}
<div class="main-panel">
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
        <div class="container-fluid">
            @*<div class="navbar-wrapper">
                    <a class="navbar-brand" href="javascript:;">MOVIES LIST / ภาพยนต์</a>
                </div>*@
            <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
                <span class="sr-only">Toggle navigation</span>
                <span class="navbar-toggler-icon icon-bar"></span>
                <span class="navbar-toggler-icon icon-bar"></span>
                <span class="navbar-toggler-icon icon-bar"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-end">
                <form class="navbar-form">
                    <div class="input-group no-border">
                        <input type="text" value="" class="form-control" placeholder="Search...">
                        <button type="submit" class="btn btn-white btn-round btn-just-icon">
                            <i class="material-icons">search</i>
                            <div class="ripple-container"></div>
                        </button>
                    </div>
                </form>
                <ul class="navbar-nav">
                    <li class="nav-item dropdown">
                        <a class="nav-link" href="javascript:;" id="navbarDropdownProfile" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="material-icons">person</i>
                            <p class="d-lg-none d-md-block">
                                Account
                            </p>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownProfile">
                            <a class="dropdown-item" href="@Url.Action("Index","MemberList")">Settings</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="~/Login/LogOut">Log out</a>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- End Navbar -->
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header card-header-primary">
                            <h4 class="card-title ">MOVIES LIST / ภาพยนต์</h4>
                            <p class="card-category">ภาพยนต์ทั้งหมด</p>
                        </div>
                        <div class="card-body">
                            <div style="float:right">
                                @ViewBag.Message
                                @using (Html.BeginForm("ExportToExcel", "LogVisit", FormMethod.Post))
                                {
                                    <button type="submit" id="btnExport" style="margin-top:-10px;" class="btn btn-rounded btn-warning"><i class="icon-printer mr-2"></i> Export</button>
                                }
                            </div>
                            <div class="table-responsive">
                                <table class="table">
                                    <tr class=" text-primary">
                                        <th class="align-middle" style="width: 100px;text-align: center;">No / ลำดับ</th>
                                        <th class="align-middle" style="text-align:center;">Name / ชื่อภาพยนต์</th>
                                        <th class="align-middle" style="width: 200px;text-align: center;">Rating / คะเเนน</th>
                                        <th class="align-middle" style="width: 250px;text-align: center;">Date / วันที่อัพเดต</th>
                                        <th class="align-middle" style="width: 50px;text-align: center;">แก้ไข</th>
                                    </tr>
                                    <tbody>
                                        @if (Model != null && Model.Count() != 0)
                                        {
                                            foreach (var item in Model)
                                            {
                                                <tr class="text-center">
                                                    <td> @Html.DisplayFor(modelItem => item.num)</td>
                                                    <td class="text-center"> @Html.DisplayFor(modelItem => item.name)</td>
                                                    <td> @Html.DisplayFor(modelItem => item.type)</td>
                                                    <td> @Html.DisplayFor(modelItem => item.create_date)</td>
                                                    <td>

                                                        @using (Html.BeginForm("Edit", "Menubar", new { id = item.id }, FormMethod.Get))
                                                        {
                                                            <button type="submit" rel="tooltip" title="Edit" class="btn btn-primary btn-link btn-sm">
                                                                <i class="material-icons">edit</i>
                                                            </button>
                                                        }

                                                        @using (Html.BeginForm("DeleteBar", "Menubar", new { id = item.id }, FormMethod.Post))
                                                        {
                                                            <button type="submit" rel="tooltip" title="Del" class="btn btn-danger btn-link btn-sm">
                                                                <i class="material-icons">close</i>
                                                            </button>
                                                        }
                                                    </td>
                                                </tr>
                                            }
                                        }
                                        else
                                        {
                                            <tr class="text-center">
                                                <td colspan="6">
                                                    No Data !!
                                                </td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                            @{
                                if (Convert.ToInt32(ViewBag.Count) > ViewBag.Rows)
                                {
                                    <div class="justify-content-center row">
                                        @if (Model != null)
                                        {
                                            @Html.PagedListPager(Model, Page => Url.Action("Index", "Menubar", new { Page }))
                                        }
                                    </div>
                                }
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>