Movie/Movie/Controllers/Admin/MovieListController.cs
using DocumentFormat.OpenXml.Office2010.Excel;
using Movie.Models.Component;
using Movie.Models.Dao;
using Movie.Models.Dto;
using MySqlConnector;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Movie.Controllers.Admin
{
    public class MovieListController : Controller
    {

        Permission checkuser = new Permission();
        // GET: MovieList
        public ActionResult Index(string start_date, string stop_date, string keyword, string drp,  int? page)
        {
            checkuser.chkrights("admin");
            var data = MovieListDao.Instance.GetDataList();
            int rows = Util.NVLInt(Varible.Config.page_rows);
            var count = data.Count;
            TempData["data"] = data.ToList().ToPagedList(page ?? 1, rows);
            if (keyword != null)
            {
                TempData["data"] = data.Where(x => x.movies.Contains(keyword) || keyword == null).ToList().ToPagedList(page ?? 1, Util.NVLInt(rows));
            }
            Session["Search"] = DropdownDao.Instance.GetDrpSearch();
            Session["Count"] = count;
            Session["Rows"] = rows;

            ViewBag.Search = Session["Search"];
            ViewBag.Count = Session["Count"];
            ViewBag.Rows = Session["Rows"];

            return View(TempData["data"]);
        }
    
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(MovieListDto model)
        {
            try
            {
                string result = MovieListDao.Instance.SaveDataList(model, "add");
                if (result != "OK")
                {
                    ViewBag.Message = result;
                    ModelState.Clear();
                }
                else
                {

                    ViewBag.Message = "Successfully !!";
                    //KRPBL.Component.Common.Form.SetAlertMessage(this,"ไม่พบ User ID ที่ระบุ กรุณาตรวจสอบ");
                    ModelState.Clear();
                }
                return View();
            }
            catch (Exception e)
            {
                ViewBag.Message = "Error : " + e.Message;
                return View();
            }
        }
        public ActionResult Edit(int id)
        {
            var model = MovieListDao.Instance.GetDataList().Find(smodel => smodel.id == id);
            return View(model);
        }
        // POST: ContentList/Edit/5
        [HttpPost]
        public ActionResult Edit(MovieListDto model)
        {
            try
            {

                string result = MovieListDao.Instance.SaveDataList(model, "edit");
                if (result != "OK")
                {
                    ViewBag.Message = result;
                }
                else
                {
                    return RedirectToAction("Index");
                }
                return View();
            }
            catch
            {
                return View();
            }
        }
        public ActionResult Delete(MovieListDto model)
        {
            try
            {
                string result = MovieListDao.Instance.SaveDataList(model, "del");
                if (result == "OK")
                {
                    ViewBag.Message = "Student Deleted Successfully";
                }
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                ViewBag.Message = "Error : " + e.Message.ToString();
                return View();
            }
        }
        public ActionResult UploadFiles(HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var result = FileUploadDao.Instance.Upload(file);



                    ViewBag.FileStatus = "File uploaded successfully.";
                }
                catch (Exception ex)
                {
                    ViewBag.FileStatus = "Error while file uploading."; ;
                }
            }
            return View("Index");
        }
    }

}

Movie/Movie/Views/MovieList/Create.cshtml
@model Movie.Models.Dto.MovieListDto
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout_admin.cshtml";
}

@using (Html.BeginForm("Create", "MovieList"))
    {
        @Html.AntiForgeryToken()
        <div class="main-panel">
            <!-- End Navbar -->
            <div class="content">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-12 ml-auto mr-auto">
                            <div class="card">
                                <div class="card-header card-header-primary">
                                    <h4 class="card-title">MANAGE / การจัดการ</h4>
                                    <p class="card-category">@Html.ValidationSummary(true, "", new { @class = "text-danger" })</p>
                                </div>
                                <div class="card-body">
                                    <h4 class="card-title">@ViewBag.Message</h4>
                                    <div class="table-responsive table-upgrade">
                                        <table class="table">
                                            <thead>
                                                <tr>
                                                    <th class="text-center">Name / ชื่อภาพยนต์ </th>
                                                    <th class="text-center">Url / ที่อยู่ </th>
                                                    <th class="text-center">Teaser / ตัวอย่างหนัง </th>
                                                </tr>
                                                <tr>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <td>
                                                        @Html.EditorFor(model => model.movies, new { htmlAttributes = new { @class = "form-control" } })
                                                        @Html.ValidationMessageFor(model => model.movies, "", new { @class = "text-danger" })
                                                    </td>
                                                    <td>
                                                        @Html.EditorFor(model => model.url, new { htmlAttributes = new { @class = "form-control" } })
                                                        @Html.ValidationMessageFor(model => model.url, "", new { @class = "text-danger" })
                                                    </td>
                                                    <td>
                                                        @Html.EditorFor(model => model.teaser, new { htmlAttributes = new { @class = "form-control" } })
                                                        @Html.ValidationMessageFor(model => model.teaser, "", new { @class = "text-danger" })
                                                    </td>
                                                </tr>
                                            </tbody>
                                        </table>
                                        <table class="table">
                                            <thead>
                                                <tr>
                                                    <th class="text-center">Info / เรื่องย่อ </th>
                                                    <th class="text-center">Sound / เสียง</th>
                                                    <th class="text-center">Hours / เวลา</th>

                                                </tr>
                                                <tr>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <td>
                                                        @Html.EditorFor(model => model.info, new { htmlAttributes = new { @class = "form-control" } })
                                                        @Html.ValidationMessageFor(model => model.info, "", new { @class = "text-danger" })
                                                    </td>
                                                    <td>
                                                        @Html.EditorFor(model => model.sound, new { htmlAttributes = new { @class = "form-control" } })
                                                        @Html.ValidationMessageFor(model => model.sound, "", new { @class = "text-danger" })
                                                    </td>
                                                    <td>
                                                        @Html.EditorFor(model => model.time, new { htmlAttributes = new { @class = "form-control" } })
                                                        @Html.ValidationMessageFor(model => model.time, "", new { @class = "text-danger" })
                                                    </td>

                                                </tr>
                                            </tbody>
                                        </table>
                                        <table class="table">
                                            <thead>
                                                <tr>
                                                    <th class="text-center">Alt / ALt </th>
                                                    <th class="text-center">HD / ความคมชัด </th>
                                                    <th class="text-center">Year / ปี </th>
                                                </tr>
                                                <tr>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <td>
                                                        @Html.EditorFor(model => model.alt, new { htmlAttributes = new { @class = "form-control" } })
                                                        @Html.ValidationMessageFor(model => model.alt, "", new { @class = "text-danger" })
                                                    </td>
                                                    <td>
                                                        @Html.EditorFor(model => model.type, new { htmlAttributes = new { @class = "form-control" } })
                                                        @Html.ValidationMessageFor(model => model.type, "", new { @class = "text-danger" })
                                                    </td>
                                                    <td>
                                                        @Html.EditorFor(model => model.year, new { htmlAttributes = new { @class = "form-control" } })
                                                        @Html.ValidationMessageFor(model => model.year, "", new { @class = "text-danger" })
                                                    </td>
                                                </tr>
                                            </tbody>
                                        </table>
                                        <table class="table">
                                            <thead>
                                                <tr>
                                                    <th class="text-center">Code / รหัส </th>
                                                    <th class="text-center">Rating / คะเเนน</th>
                                                    <th class="text-center">File / ไฟล์</th>
                                                </tr>
                                                <tr>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <td>
                                                        @Html.EditorFor(model => model.code, new { htmlAttributes = new { @class = "form-control" } })
                                                        @Html.ValidationMessageFor(model => model.code, "", new { @class = "text-danger" })
                                                    </td>
                                                    <td class="text-center">
                                                        @Html.EditorFor(model => model.rating, new { htmlAttributes = new { @class = "form-control" } })
                                                        @Html.ValidationMessageFor(model => model.rating, "", new { @class = "text-danger" })
                                                    </td>
                                                    <td class="text-center">
                                                        @Html.EditorFor(model => model.img_head, new { htmlAttributes = new { type = "file" } })
                                                        @Html.ValidationMessageFor(model => model.img_head)
                                                    </td>
                                                </tr>
                                            </tbody>
                                        </table>
                                        <div class="form-group text-center">
                                            <div class="col-md-offset-2 col-md-12">
                                                <input type="button" value="Back" onclick="location.href='@Url.Action("Index", "MovieList")'" class="btn btn-danger" />
                                                <input type="submit" value="Save" class="btn btn-primary" />
                                            </div>
                                        </div>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    }

Movie/Movie/Views/MovieList/Edit.cshtml
@model Movie.Models.Dto.MovieListDto
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout_admin.cshtml";
}

@using (Html.BeginForm("Edit", "MovieList"))
{
    @Html.AntiForgeryToken()
    <div class="main-panel">
        <!-- End Navbar -->
        <div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-12 ml-auto mr-auto">
                        <div class="card">
                            <div class="card-header card-header-primary">
                                <h4 class="card-title">MANAGE / การจัดการ</h4>
                                <p class="card-category">@Html.ValidationSummary(true, "", new { @class = "text-danger" })</p>
                            </div>
                            <div class="card-body">
                                <h4 class="card-title">@ViewBag.Message</h4>
                                <div class="table-responsive table-upgrade">
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th class="text-center">Name / ชื่อภาพยนต์ </th>
                                                <th class="text-center">Url / ที่อยู่ </th>
                                                <th class="text-center">Teaser / ตัวอย่างหนัง </th>
                                            </tr>
                                            <tr>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>
                                                    @Html.EditorFor(model => model.movies, new { htmlAttributes = new { @class = "form-control" } })
                                                    @Html.ValidationMessageFor(model => model.movies, "", new { @class = "text-danger" })
                                                </td>
                                                <td>
                                                    @Html.EditorFor(model => model.url, new { htmlAttributes = new { @class = "form-control" } })
                                                    @Html.ValidationMessageFor(model => model.url, "", new { @class = "text-danger" })
                                                </td>
                                                <td>
                                                    @Html.EditorFor(model => model.teaser, new { htmlAttributes = new { @class = "form-control" } })
                                                    @Html.ValidationMessageFor(model => model.teaser, "", new { @class = "text-danger" })
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th class="text-center">Info / เรื่องย่อ </th>
                                                <th class="text-center">Sound / เสียง</th>
                                                <th class="text-center">Hours / เวลา</th>

                                            </tr>
                                            <tr>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>
                                                    @Html.EditorFor(model => model.info, new { htmlAttributes = new { @class = "form-control" } })
                                                    @Html.ValidationMessageFor(model => model.info, "", new { @class = "text-danger" })
                                                </td>
                                                <td>
                                                    @Html.EditorFor(model => model.sound, new { htmlAttributes = new { @class = "form-control" } })
                                                    @Html.ValidationMessageFor(model => model.sound, "", new { @class = "text-danger" })
                                                </td>
                                                <td>
                                                    @Html.EditorFor(model => model.time, new { htmlAttributes = new { @class = "form-control" } })
                                                    @Html.ValidationMessageFor(model => model.time, "", new { @class = "text-danger" })
                                                </td>

                                            </tr>
                                        </tbody>
                                    </table>
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th class="text-center">Alt / ALt </th>
                                                <th class="text-center">HD / ความคมชัด </th>
                                                <th class="text-center">Year / ปี </th>
                                            </tr>
                                            <tr>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>
                                                    @Html.EditorFor(model => model.alt, new { htmlAttributes = new { @class = "form-control" } })
                                                    @Html.ValidationMessageFor(model => model.alt, "", new { @class = "text-danger" })
                                                </td>
                                                <td>
                                                    @Html.EditorFor(model => model.type, new { htmlAttributes = new { @class = "form-control" } })
                                                    @Html.ValidationMessageFor(model => model.type, "", new { @class = "text-danger" })
                                                </td>
                                                <td>
                                                    @Html.EditorFor(model => model.year, new { htmlAttributes = new { @class = "form-control" } })
                                                    @Html.ValidationMessageFor(model => model.year, "", new { @class = "text-danger" })
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                    <div class="form-group text-center">
                                        <div class="col-md-offset-2 col-md-12">
                                            <input type="button" value="Back" onclick="location.href='@Url.Action("Index", "MovieList")'" class="btn btn-danger" />
                                            <input type="submit" value="Save" class="btn btn-primary" />
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

Movie/Movie/Views/MovieList/Index.cshtml
@using PagedList;
@using PagedList.Mvc;
@model IPagedList<Movie.Models.Dto.MovieListDto>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout_admin.cshtml";
}
<div class="main-panel">
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
        <div class="container-fluid">
            @*<div class="navbar-wrapper">
                <a class="navbar-brand" href="javascript:;">MOVIES LIST / ภาพยนต์</a>
            </div>*@
            <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
                <span class="sr-only">Toggle navigation</span>
                <span class="navbar-toggler-icon icon-bar"></span>
                <span class="navbar-toggler-icon icon-bar"></span>
                <span class="navbar-toggler-icon icon-bar"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-end">
                <form class="navbar-form">
                    <div class="input-group no-border">
                        @using (Html.BeginForm("", "Home", FormMethod.Post))
                        {
                            @Html.TextBox("keyword", ViewBag.CurrentFilter as string,new { @class = "form-control", placeholder = "Search" })
                            @*<input type="text" value="" class="form-control" placeholder="Search...">*@
                            <button type="submit" class="btn btn-white btn-round btn-just-icon">
                                <i class="material-icons">search</i>
                                <div class="ripple-container"></div>
                            </button>
                        }
                    </div>
                </form>
                <ul class="navbar-nav">
                    <li class="nav-item dropdown">
                        <a class="nav-link" href="javascript:;" id="navbarDropdownProfile" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="material-icons">person</i>
                            <p class="d-lg-none d-md-block">
                                Account
                            </p>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownProfile">
                            <a class="dropdown-item" href="@Url.Action("Index","MemberList")">Settings</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="~/Login/LogOut">Log out</a>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- End Navbar -->
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header card-header-primary">
                            <h4 class="card-title ">MOVIES LIST / ภาพยนต์</h4>
                            <p class="card-category">ภาพยนต์ทั้งหมด</p>
                        </div>
                        <div class="card-body">
                            <div style="float:right">
                                @using (Html.BeginForm("ExportToExcel", "LogVisit", FormMethod.Post))
                                {
                                    <button type="submit" id="btnExport" style="margin-top:-10px;" class="btn btn-rounded btn-warning"><i class="icon-printer mr-2"></i> Export</button>
                                }
                            </div>
                            <div class="table-responsive">
                                <table class="table">
                                    <tr class   =" text-primary">
                                        <th class="align-middle" style="width: 100px;text-align: center;">No / ลำดับ</th>
                                        <th class="align-middle" style="text-align:center;">Name / ชื่อภาพยนต์</th>
                                        <th class="align-middle" style="width: 200px;text-align: center;">Rating / คะเเนน</th>
                                        <th class="align-middle" style="width: 250px;text-align: center;">Date / วันที่อัพเดต</th>
                                        <th class="align-middle" style="width: 50px;text-align: center;">แก้ไข</th>
                                    </tr>
                                    <tbody>
                                        @if (Model != null && Model.Count() != 0)
                                        {
                                            foreach (var item in Model)
                                            {
                                        <tr class="text-center">
                                            <td> @Html.DisplayFor(modelItem => item.num)</td>
                                            <td class="text-center"> @Html.DisplayFor(modelItem => item.movies)</td>
                                            <td> @Html.DisplayFor(modelItem => item.rating)</td>
                                            <td> @Html.DisplayFor(modelItem => item.create_date)</td>
                                            <td>

                                                @using (Html.BeginForm("Edit", "MovieList", new { id = item.id }, FormMethod.Get))
                                                {
                                                    <button type="submit" rel="tooltip" title="Edit" class="btn btn-primary btn-link btn-sm">
                                                        <i class="material-icons">edit</i>
                                                    </button>
                                                }

                                                @using (Html.BeginForm("Delete", "MovieList", new { id = item.id }, FormMethod.Post))
                                                {
                                                    <button type="submit" rel="tooltip" title="Del" class="btn btn-danger btn-link btn-sm">
                                                        <i class="material-icons">close</i>
                                                    </button>
                                                }
                                            </td>
                                        </tr>
                                            }
                                        }
                                        else
                                        {
                                            <tr class="text-center">
                                                <td colspan="6">
                                                    No Data !!
                                                </td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                            @{
                                if (Convert.ToInt32(ViewBag.Count) > ViewBag.Rows)
                                {
                                    <div class="justify-content-center row">
                                        @if (Model != null)
                                        {
                                            @Html.PagedListPager(Model, Page => Url.Action("Index", "MovieList", new { Page }))
                                        }
                                    </div>
                                }
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>